---
title: "Gov 50 Final Project"
author: "Your Name Here"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to how media coverage of the election changes the behavior of it. 




Have you ever wondered how national news media coverage affects elections?  In this study, I plan to examine how media coverage affects the behavior of the electorate. I hypothesize that national news media coverage will likely substantially influence the electorate's behavior. I affirm this because most citizens believe everything they get from news sources, and by believing the information, they are adopting the same political beliefs as the news source–ultimately shifting the outcome of the election. News sources can also push the political agenda by telling one side of a story, which electorates sympathize with and conform to the propaganda the sources are trying to push. However, this acutely insinuates that all news sources are bad, which is incredibly untrue. It can shine a light on ideals or actions candidates did– changing how electorates view the candidate they support. The explanatory variable is whether the town got Fox News; if they did, they would project conservative news to the subscribers. This is the column = subrf2000. The outcomes are measured in the percentage of the town that voted for the Republican political party. The data supports my hypothesis that media coverage affects the behavior of the electorate because it is seen through the data that a town that had Fox News subscribers has shifted towards the Republican party as elections went on because the percentage of the town voting right-winged grew or increased. Subsequently, this affirms that media has an effect on the behavior of the electorate.